services:
  postgres:
    image: postgres:14
    container_name: docker-postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dileep@2025
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql/ddl:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: docker-pipeline
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../.env
    volumes:
      - ..:/app
    command: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
